### ISSUE TITLE
🍺🤩 Tallinn BeerJS v0.0.1(15.01.2018 Tartu Bar) 

### ISSUE THREAD

**Issue by drownbes** [beerjs/tallinn#1]
Issue for collecting topics for the first event.

**Comment by drownbes** [comment]
Let me start. I want to discuss:
1. Ongoing trends in frontend world for 2019
2. React state management outside of redux and mobx
3. Production use-cases of web-assembly

**Comment by Param-Harrison** [comment]
- Use cases for JAMStack - Pros and Cons

**Comment by alexjs-dev** [comment]
VueJS

**Comment by JuanDelgadillo** [comment]
TensorFlow.js, how the AI ecosystem is evolving in JS.

**Comment by dknight** [comment]
TypeScript - pros and cons, yes or no?

**Comment by drownbes** [comment]
Thanks everybody for coming. 🥂

It was really unexpected that so many people would come! 

Well done everybody. 

To the moon! 🚀🌝
![2019-01-16 11 27 34](https://user-images.githubusercontent.com/1948516/51444791-f80a2580-1d04-11e9-828a-d03072de4e31.jpg)
