### ISSUE TITLE
🍺🕷 Tallinn BeerJS v2019.03.07 (Põhjala Brewery)

### ISSUE THREAD

**Issue by drownbes** [beerjs/tallinn#3]
Issue for collecting topics for event

**Comment by fljot** [comment]
architecture,
reactive stuff (RxJS, MobX, ...?),
advanced TypeScript whatever,
logging (especially in browser),
culture (in big teams),
cool places to work?

**Comment by Darwinut** [comment]
- Portfolio
- Blog
- Game Development (Phaser, ..? )
- Interesting libraries?

**Comment by Chris-Golle** [comment]
Speed and website animations: What is recommended? jQuery?

**Comment by taokakao** [comment]
> Speed and website animations: What is recommended? jQuery?

Such a great topic! Would also love to hear about jQuery!

**Comment by ShintoTuna** [comment]
React Context and Hooks in real life. Performance, testing etc
